"""Image post-processing — Pillow only (no SDK, no numpy).

Transcode generated bytes to the requested output format, and chroma-key a flat
background color to transparency. Pure functions over PIL Images, fully
offline-testable.
"""
from __future__ import annotations

import io
from pathlib import Path

from PIL import Image, ImageChops

_COLOR_NAMES = {
    "magenta": (255, 0, 255),
    "green": (0, 255, 0),
    "cyan": (0, 255, 255),
    "white": (255, 255, 255),
    "black": (0, 0, 0),
}


class ImagingError(Exception):
    """Raised on undecodable image bytes, an unsavable path, or a bad color."""


def decode(data: bytes) -> Image.Image:
    try:
        img = Image.open(io.BytesIO(data))
        img.load()
        return img
    except Exception as exc:  # noqa: BLE001 — PIL raises a variety of types
        raise ImagingError(f"could not decode image bytes: {exc}") from exc


def save_image(img: Image.Image, out_path: str) -> str:
    path = Path(out_path)
    fmt = path.suffix.lower().lstrip(".")
    to_save = img
    if fmt in ("jpg", "jpeg") and img.mode not in ("RGB", "L"):
        to_save = img.convert("RGB")  # JPEG can't hold alpha
    try:
        to_save.save(path)
    except (OSError, ValueError, KeyError) as exc:
        raise ImagingError(f"could not save image to {out_path}: {exc}") from exc
    return str(path.resolve())


def parse_color(s: str) -> tuple[int, int, int]:
    key = s.strip().lower()
    if key in _COLOR_NAMES:
        return _COLOR_NAMES[key]
    hexs = key[1:] if key.startswith("#") else key
    if len(hexs) == 6:
        try:
            return (int(hexs[0:2], 16), int(hexs[2:4], 16), int(hexs[4:6], 16))
        except ValueError:
            pass
    raise ImagingError(f"unrecognized color {s!r} (use #RRGGBB or one of {sorted(_COLOR_NAMES)})")
